name: "wiki-infra-deploy"
description: "Deploy Wiki infrastructure"

inputs:
  environment-name:
    description: ""
    required: true

runs:
  using: "composite"
  steps:

    - name: Deploy Resource Group template
      id: deployRG
      uses: azure/arm-deploy@v1
      with:
        scope: subscription
        template: ./wiki/arm/resourceGroup.json
        parameters: "./wiki/arm/parameters/${{ inputs.environment-name }}.json"

    - name: Deploy Resources template
      uses: azure/arm-deploy@v1
      with:
        scope: resourcegroup
        resourceGroupName: ${{ steps.deployRG.outputs.name }}
        template: ./wiki/arm/resources.json
        parameters: >
          ./wiki/arm/parameters/${{ inputs.environment-name }}.json'
          scripts-repo-branch=${{ github.ref_name }}
