name: wiki-infra-cd

on:
  workflow_dispatch:
    inputs:
      environment:
        required: true
        description: "Target environment for Wiki infrastructure deployment"
        type: choice
        options:
          - "Sandbox - Anton Boyko 01"

jobs:
  wiki-infra-deploy:
    uses: ${{github.repository}}/.github/workflows/wiki-infra-deploy.yml@${{github.ref_name}}
    with:
      EnvironmentName: ${{ github.event.inputs.environment }}
    secrets:
      AzureCredentials: ${{ secrets.AZURE_CREDENTIALS }}
