name: wiki-infra-cd

on:
  workflow_dispatch:
    inputs:
      environment:
        required: true
        description: "Target environment for Wiki infrastructure deployment"
        type: choice
        options:
          - "Sandbox - Anton Boyko 01"

jobs:
  deploy:
    runs-on: ubuntu-20.04
    environment: ${{ github.event.inputs.environment }}
    steps:
      - uses: actions/checkout@v2

      - uses: azure/login@v1
        name: Login to Azure
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - uses: ./.github/actions/wiki-infra-deploy
        name: Deploy Wiki infrastructure to target environment
        with:
          environment-name: ${{ github.event.inputs.environment }}

  # wiki-infra-deploy:
  #   uses: ${{github.repository}}/.github/workflows/wiki-infra-deploy.yml@${{github.ref_name}}
  #   with:
  #     EnvironmentName: ${{ github.event.inputs.environment }}
  #   secrets:
  #     AzureCredentials: ${{ secrets.AZURE_CREDENTIALS }}
