name: wiki-infra-cd

on:
  workflow_dispatch:
    inputs:
      environment:
        required: true
        description: 'Target environment for Wiki infrastructure deployment'
        type: choice
        options:
        - 'Sandbox - Anton Boyko 01'

jobs:
  deploy:
    runs-on: ubuntu-20.04
    environment: ${{ github.event.inputs.environment }}

    steps:
      - uses: actions/checkout@v2

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          
      - name: Deploy ARM template
        uses: azure/arm-deploy@v1
        with:
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
          resourceGroupName: ${{ secrets.AZURE_RESOURCEGROUP_NAME }}
          template: ./wiki/arm/template.json
          parameters: storage-name=abo2021test01
